# Generated by Django 5.1.2 on 2024-10-31 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('habit_type', models.CharField(choices=[('time', 'Time-based'), ('count', 'Count-based')], max_length=10)),
                ('target_count', models.IntegerField(blank=True, null=True)),
                ('total_time', models.DurationField(blank=True, null=True)),
                ('streak', models.IntegerField(default=0)),
                ('frequency', models.CharField(choices=[('daily', 'Günlük'), ('weekly', 'Haftalık'), ('monthly', 'Aylık')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
