# Generated by Django 5.1.2 on 2024-11-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
