# Generated by Django 5.1.2 on 2025-01-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='target_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
