# Generated by Django 5.1.2 on 2025-01-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_target_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='completed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habit',
            name='completion_dates',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='habit',
            name='last_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
