# Generated by Django 5.1.2 on 2025-01-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habit_completed_count_habit_completion_dates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='last_completed_date',
            field=models.DateField(blank=True, default=str, null=True),
        ),
    ]
