# Generated by Django 5.1.2 on 2025-01-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_last_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='last_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
